[project]
name = "hass-findmy"
version = "0.0.1"
requires-python = ">=3.14.2,<3.15"
dependencies = ["homeassistant>=2026.9.3", "findmy>=0.10.2"]

[dependency-groups]
dev = ["basedpyright>=1.40.1", "pre-commit>=4.6.2", "ruff>=0.16.8"]

[tool.pyright]
reportMissingTypeStubs = false

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "ANN002", # annotations on `*args`
    "ANN003", # annotations on `**kwargs`

    "COM812", # missing trailing comma

    "CPY001", # missing copyright notice

    "S101", # assert

    "D", # Documentation
]
